### ISSUE TITLE
AVR-569 Not adding passive bonus from Observant Feat

### ISSUE THREAD

**Issue by shaylic** [avrae/avrae#1102] opened 2020-05-24 21:11 UTC
**Describe the bug**
Observant is a feat that adds +5 to Passive Wisdom (Perception) and Passive Intelligence (Investigation) scores. Avrae when adding a character from DND Beyond does not add this bonus if feat is being used.

**Severity**
Low

**Context**
The command run that the bug occurs in and any choice trees.

**To Reproduce**
1. Create character on DnD Beyond with Observant Feat
2. Add character to Discord
3. Scroll down to Senses
4. See error as Passive perception will be off

**Expected behavior**
Passive Perception will be off.

**Screenshots**

https://share.icloud.com/photos/0F-FFXLReb__3CSUzgX6pvD5g

https://share.icloud.com/photos/0TZOL0EP6BmeW-kbbCulJG9hQ

**Additional context**

**Comment by Croebh** [comment] 2020-05-24 22:25
Dupe of #974

**Closed** 2020-05-26 18:43 UTC
Labels: bug, duplicate
