### ISSUE TITLE
AVR-337 Warlock spell slots won't work for custom spells of lower level

### ISSUE THREAD

**Issue by ArtOfCombat** [avrae/avrae#655] opened 2019-06-26 04:37 UTC
**Describe the bug**
When using the !cast command with a first-level spell added to Avrae.io (in this case, witch bolt), I am told I have no spell slots and cannot cast the spell, despite having just taken a long rest, as I can only cast it as second level, and thus don't have first-level slots. I am playing a level 3 warlock.

**Severity**
Medium

**Context**
!cast a level 1 spell on a warlock with only higher-level slots. Might only apply to custom spells.

**To Reproduce**
1: Make a level-3 Warlock character sheet in G-docs and import
2: With only level 2 spell slots, try to cast a level 1 spell on your level 2 list.

**Expected behavior**
The spell is cast at higher level.

**Screenshots**
N/A

**Additional context**
This bug was first noticed with a custom spell, but applies to all spells.

**Comment by mommothazaz123** [comment] 2019-06-26 04:43
Hi Art, thanks for your report! This is technically intended behaviour as Avrae doesn't automatically upcast when you lack lower-level spell slots; to do so, you can pass the `-l 2` argument to cast at level 2.

Some users on the [Avrae Dev Server](https://support.avrae.io) have made scripts to handle this automatically. I'll consider making upcasting the default behaviour for warlocks, though.

**Comment by mommothazaz123** [comment] 2019-07-08 21:36
Copied from the Avrae Dev server:
> RFC: AVR-337
> 
> When a warlock casts a spell, right now they have to explicitly pass the spell's level with -l. There are a few approaches we can take to this:
> 
> 1. Don't change anything.
> 2. When casting a spell, default to the next-lowest-level available spell slot.
> 3. When casting a spell, default to the next-lowest-level available spell slot, but only if the max for the current level is 0.
> 
> The difference between cases 2 and 3 are:
> case 2: A level 3 bard (4L1, 2L2) uses all their L1 slots and tries to cast a L1 spell. Avrae uses a L2 slot for them.
> case 3: A level 3 bard (4L1, 2L2) uses all their L1 slots and tries to cast a L1 spell. Avrae displays the current error. (i.e., only upcast automatically for warlocks)

The agreed-upon behaviour seems to be case 3. Marking as P3.

Also TODO: add some nicer error embeds when casting to make the missing resource more clear.

**Closed** 2019-07-11 18:00 UTC
Labels: P3: Medium, bug
